SAVE = "icons/ic_save_white_24dp_2x.png"
START = "icons/ic_play_arrow_white_24dp_2x.png"
PAUSE = "icons/ic_pause_white_24dp_2x.png"
AUTO_SCROLL = "icons/ic_vertical_align_bottom_white_24dp_2x.png"
CLEAR = "icons/ic_delete_sweep_white_24dp_2x.png"
